### ISSUE TITLE
Select All is not working with AJAX data

### ISSUE THREAD

**Issue by esaesa** [kartik-v/yii2-widget-select2#168]
## Steps to reproduce the issue

1. Use the demo example at http://demos.krajee.com/widget-details/select2#usage-ajax.
2. Add  `',multiple' => true` to `options`.
3. Show the view and start searching.
4. Click Select all.

## Expected behavior and actual behavior

When I follow those steps, I see...
Nothing happened

I was expecting...
All items is selected

## Environment
Win7 - Chrome - PHP5.6 Yii 2.0.10

#### Browsers

- [x] Google Chrome

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-widget-select2 version: 2.0.9

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins

**Comment by kartik-v** [comment]
The core [select2 plugin](https://github.com/select2/select2) does not support `Select All` and such functionality. These are additional enhancements added specifically in this widget.

For non ajax based selects it was possible to write a Select All routine because the native select options are already rendered and it is easy to select these options and trigger a change of the select input. 

But for ajax based search the core plugin does not render any options unless you have selected them itself. So basically the select all functionality will not work.

Hence currently I am disabling the Select All functionality for ajax uploads via another enhancement.

**Comment by NickvdMeij** [comment]
@kartik-v Is there in the meantime a solution to this problem? Would love to have this feature.
