### ISSUE TITLE
reload select2 after activeForm was submitted

### ISSUE THREAD

**Issue by Zmey2701** [kartik-v/yii2-widget-select2#19]
Hi. I'm using the widget with ActiveForm like in the demo examples on your page. But when I submit the form and get it reloaded, the select2 fields are spinning all the time. The fields are not loaded completely as full pretty Select2. In returned page code I see just an input with value. I can see the id I've selected by value before through the 'pluginLoading' => false -- in this case the field is displayed as simple input with Id of previously selected item.
I've just thought it looks like the same issue with https://github.com/kartik-v/yii2-widget-select2/issues/18 but it's closed. Could you describe the answer you found out more completely?

Thanks.

**Comment by kartik-v** [comment]
If you are loading form and inputs via AJAX (i.e. javascript) - you need to write the correct code to reinitialize all your javascript / jquery plugins like Select2.

The extensions like most Yii extensions are designed for jquery plugins to autoinitialize on document ready. 

Any other scenario of you having an ajax based load that does not trigger document ready is outside the scope of the extension, as it depends on your application code and what and how you are rendering via ajax.

One solution/option in Yii to render all jquery related plugins via ajax correctly is to use `renderAjax` method instead of `renderPartial`.

**Comment by Zmey2701** [comment]
Hi.
Thank you for the response and suggestion to solve my problem.

I've tried your suggestion but it doesn't work. The result only differs with the previous that all the page is returned. The page is returning with all the scripts and styles in it's body but they are not fired after the page is returned. The event document.ready you mentioned isn't fired after renderAjax returns the rendered page.

As far as I understood the way out is to fire document.ready event to reload scripts and styles? Or maybe there is any method in Select2 widget to reload itself or reinit after Ajax call was fired? 
 
Have you any other suggestion what the problem could be? Or in what direction I have to dig?

**Comment by kartik-v** [comment]
You can reinitialize the plugin on AJAX success/completion. You need to do this for all javascript/jquery based plugins. With all of Krajee extensions/plugins - this is easier because the plugin options and settings are internally stored in a data variable.

So you can run this javascript and call it ON ajax success to reinitialize select2 for example:

```js
var $el = $("#input-id"), // your input id for the HTML select input
    settings = $el.attr('data-krajee-select2');
settings = window[settings];
// reinitialize plugin
$el.select2(settings);
```

**Comment by Zmey2701** [comment]
Hi!

Thanks a lot for the complete answer. The first one js works perfectly! That was a problem.

**Comment by harryalwanga** [comment]
Hi guys I have faced the same problem but unfortunately this solution has not worked for me. Is there something I am doing wrong?

I have added this in my view

<script>
var $el = $("#title_id"), // your input id for the HTML select input
    settings = $el.attr('data-krajee-select2');
settings = window[settings];
// reinitialize plugin
$el.select2(settings);
</script>

**Comment by paskuale75** [comment]
I've this but nothing happens
```
'pluginEvents' => [
            "tabsX.click" => "function() { console.log('tabsX.click'); }",
            "tabsX.beforeSend" => "function() { console.log('tabsX.beforeSend'); }",
            "tabsX.success" => "function(data) {
                        console.dir(data);
                        var tab = '' + $(data.target).data('tab'); 
                        
                        //Select2 reinit
                        var el = $('#muAttribute'), // your input id for the HTML select input
                            settings = el.attr('data-krajee-select2'),
                            id = el.attr('id');
                            settings = window[settings];

                        // reinitialize plugin
                            el.select2(settings);
                        }
                        ",

            "tabsX.error" => "function() { console.log('tabsX.error'); }",
```
