### ISSUE TITLE
problem with append and Clone div that select 2 in it for multi select 2 with jquery clone

### ISSUE THREAD

**Issue by mamadza** [kartik-v/yii2-widget-select2#214]
I have two problems with select 2 at first on is ,
I render my page it renderAjax at frist on when i jump from step1 to step2 select 2 is workin correctly but when i go back to step1 and again go to step2 all select 2 don't workin and just show loading with gif

![image](https://cloud.githubusercontent.com/assets/12842935/26527949/3617d3d0-43b4-11e7-88fe-aff7b1e53ef2.png)

the second promblem is , when i go to step4 i have div and there is one select 2 in it and work correctly but in my project i need to clone that div to have another div and select2 in it , but when i clone that div with jquery but the style of select 2 mess , and happen a lot problem in it

![image](https://cloud.githubusercontent.com/assets/12842935/26527951/4c4ed356-43b4-11e7-9e02-4479f6c807ba.png)

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: last
- yii2-widget-select2 version: last

**Comment by kartik-v** [comment]
It seems a specific programming issue on your end to handle and I am not sure I can help here.

But one thing I see is that you are cloning the inputs in various parts of your code - which will cause your HTML to go corrupt and markups to break since the HTML elements will have duplicate ID attributes. The SELECT2 is also initialized based on the ID attribute and your cloning of duplicate ID attributes in HTML markup will cause jQuery plugin to misbehave.
