### ISSUE TITLE
Kartik Select2 not working after appending it with jquery

### ISSUE THREAD

**Issue by AlisherN** [kartik-v/yii2-widget-select2#273]
I have problem with kartik select2 widget. I am trying to create dynamic form with jquery. First, I created two fields with kartik select2 in div element. Then I cloned all content of the div and append it into the div. But, cloned select2 not working when it will be clicked. Could you help me?
javascript code:

```
$(document).ready(function(){
    $(document).on("click", "#add-department-btn", function(e){
      e.preventDefault();
      console.log("Clicked");

      var option_name = Math.random()*1000000;
      option_name = parseInt(option_name);
      var id = $(".add-departments-container .copyPattern").data('id');
      var row = $(".add-departments-container .copyPattern").clone().removeClass('copyPattern');

      row.appendTo(".add-departments-container");

      return false;
   });
});
```
![2018-10-15_15-54-05](https://user-images.githubusercontent.com/26760588/46950571-80da4b00-d09e-11e8-8acc-97fa0c175877.jpg)

**Comment by kartik-v** [comment]
This seems a programming error. You cannot blindly clone elements as they can cause conflicting jQuery plugin behavior and break your page. You need to handle it carefully in your programming to ensure that 
- every jQuery element is unique and does not include conflicting HTML id attributes 
- use `jQuery.clone(false) ` to not clone methods and events and reinitialize select2 plugin after the clone. (this would need you to do reading on jquery clone and how to initialize select2 plugin (there are few additional jquery behaviors within yii2 select2 widget for you to do bit more)
- alternatively instead of clone - just render the select2 via AJAX... using yii2 renderAjax.... this will be easiest to get and configure all Yii2 select2 widget behavior and rendering defaults.

**Comment by kyocom123** [comment]
i cannot render select2 with renderAjax, select2 not show option
