### ISSUE TITLE
Problem with "multiple" Select 2 widgets within bootstrap tabs

### ISSUE THREAD

**Issue by philippfrenzel** [kartik-v/yii2-widget-select2#29]
Hi, 

I have an application with multiple tabs - each tab containing the "same" table only different by a filter.

![screenshot 2015-05-10 07 00 37](https://cloud.githubusercontent.com/assets/2319890/7553107/4a7b4e90-f6e2-11e4-9e08-82c47094d802.png)

sadly only the first tab shows the select2 widget, on the second e.g. it's not appearing...

![screenshot 2015-05-10 07 01 47](https://cloud.githubusercontent.com/assets/2319890/7553110/775a0a96-f6e2-11e4-9086-4bb32982b4c0.png)

**Comment by kartik-v** [comment]
As a rule, whenever you use any such jquery plugin based inputs (like Select2), you need to check how and when you are rendering them. They will render fine only if the javascript to initialize them is called after the content is loaded and ready.

For a new page this works because the yii2-widget-select2 code calls the init script on doc ready - but for tabs or other content  - you maybe rendering the content via ajax or on click and no content is available on doc ready. So the Select2 plugin init code will not find an input to initialize on doc ready. So this needs to be done manually after ajax success OR some similar event.

**Comment by kartik-v** [comment]
As a rule, whenever you use any such jquery plugin based inputs (like Select2), you need to check how and when you are rendering them. They will render fine only if the javascript to initialize them is called after the content is loaded and ready.

For a new page this works because the yii2-widget-select2 code calls the init script on doc ready - but for tabs or other content  - you maybe rendering the content via ajax or on click and no content is available on doc ready. So the Select2 plugin init code will not find an input to initialize on doc ready. So this needs to be done manually after ajax success OR some similar event.

Yii provides a renderAjax method in Controller to render such content that also calls the scripts.

**Comment by philippfrenzel** [comment]
Hi, thanks for the update, I think it's the "dublicate id" -> actually, i have to take a closer look where to change it, as this should be done within the widget options?!
