### ISSUE TITLE
search inside modal dialog (BS5 new)

### ISSUE THREAD

**Issue by spo0okie** [kartik-v/yii2-widget-select2#341]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Create Modal (no tabindex)
2.Create Select2 inside it
3.No way to focus on select field and type a word

Yo can see it on modal demo:
https://demos.krajee.com/widget-details/select2#usage-advanced
modal search not works (Popover Works)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.6.0
- yii2-widget-select2 version: 2.2.3

## Isolating the problem
It hapens after migrating project on BS5
in BS3 tabindex "method" was working and now it not

- [x] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by mkraibt** [comment]
Related to the same issue, dropdownParent works but I noticed select2 loses all its CSS properties. Is anyone facing the same issue?
![image](https://user-images.githubusercontent.com/54493187/213368894-1dd25cab-9efb-4c73-8e05-58d51d8da293.png)
the closest thing I can get is if I use the 'default' theme but it looks different. This happens when loading in a modal only.

Also when we set dropdownParent, select2 becomes useless if we right-click and open in a new tab (usable when the form is dynamic/ template based and large that needs to open in a new tab for more real estate).

It was working before on BS3.. I only had to set global `$.fn.modal.Constructor.prototype.enforceFocus = function () { };` which doesn't work in BS5. Also tried BS4 version  `$.fn.modal.Constructor.prototype._enforceFocus = function () {};`

**Comment by strtob** [comment]
I have exactly the same problem. 
- all css will lose
- the $fn. don't work for BS5.

Does anyone have an idea how to handle this issue? :(

**Comment by strtob** [comment]
after hours of searching, removing tablindex=-1, etc. I've found the solution.

In case you use select2 with bootstrap 5 and you can't access the search input field by use of Modal, put this in you js code upfront:


` bootstrap.Modal.prototype._initializeFocusTrap = function () { return { activate: function () { }, deactivate: function () { } } };`

**Comment by mkraibt** [comment]
@strtob above code works great. Didn't even need the "dropdownParent" option. Form with select 2 is working in modal as well as if I open it in a new tab.  Thank you.
