### ISSUE TITLE
Kartik GridView with ExpandRowColumn select2 attribute disappears on detail page

### ISSUE THREAD

**Issue by alzambo** [kartik-v/yii2-widget-select2#36]
there's something wrong on a `\kartik\widgets\Select2` widget used into an `ExpandRowColumn` detail page:

![detail page][1]

  [1]: http://i.stack.imgur.com/BC59L.png

Expanding the row to show the detail page, it will show only the first select2 attribute. 

The view:

    'idAssicurato' => [
        'type'=>Form::INPUT_WIDGET,
        'label' => "Assicurato",
        'widgetClass'=>'\kartik\widgets\Select2', 
        'options'=>['data' => ArrayHelper::map(Assicurato::find()->all(), 'id', 'nomeAssicurato')]
    ]

If I use `'type'=>Form::INPUT_WIDGET` it works.
Maybe a bug?

Alex

**Comment by kartik-v** [comment]
This is a problem raised my many folks here who use jquery plugin based inputs.

It is a problem because of duplicate HTML element ID. In general you must not be duplicating the HTML element ID. You probably have the same ID across all Select2 inputs.

Ensure your Select2 input element has an unique HTML ID attribute.
