### ISSUE TITLE
can not set initValueText when using ajax and templates

### ISSUE THREAD

**Issue by asoqa** [kartik-v/yii2-widget-select2#37]
I use ajax and template with select2. But can not init the default selection value with "initValueText". However,  if I do not use template, the initValueText works fine
```
        echo $form->field($model, 'endField')->widget(Select2::classname(), [
            'name' => 'field-select2',
            'initValueText' => 'kartik-v/yii2-widgets',
            'value' => '672',
            'options' => [
                'placeholder' => 'Search for a repo ...'
            ],
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 2,
                'ajax' => [
                    'url' => Url::to([
                        'fields/ajaxfields', 'pid'=>$model->startPid
                    ]),
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }'),
                    'cache' => true
                ],
                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                'templateResult' => new JsExpression('formatRepo'),
                'templateSelection' => new JsExpression('formatRepoSelection')
            ]
        ]);
```

**Comment by kartik-v** [comment]
You may need to read Select2 plugin docs or contact the select2 plugin community for more info on how you setup the plugin for your use case.

If you have other programming queries beyond the widget, you may want to [post queries on programming help and tips in this new forum here](http://webtips.krajee.com/questions).

**Comment by KalmanBodor** [comment]
Just for the record, if others are fighting the same issue, I managed to make this work the following way:
- if you're displaying an empty form, for example when displaying a form for creating an object, use
`'options' => [ 'placeholder' => 'Search for a repo ...' ]`, but don't specify InitValue, value or data at all
- if you're displaying a form with already populated fields, maybe you want to update an already existing object, and you want to display the already saved value for the Select2 field, use `'data' => [ 1 => 'Some value' ]`, where 1 is the value, associated to the value displayed in the form. You can retrieve stuff to put in data from DB beforehand.
So when building the Select2 input, you need to check if you already have a $model, and display 'placeholder' if the $model doesn't yet exist and don't put the data key there at all, otherwise add the 'data' key and don't use 'placeholder' at all.

I think another thing to draw attention to is that the data returned by the Ajax request should contain the id and text keys, and if you're using a specific templateResult function you need to use the text keys:
`'templateResult' => new JsExpression('function(some_field_identifier) { return some_field_identifier**.text**; }')`.
This is mentioned [here](https://select2.github.io/options.html#what-properties-are-required-on-the-objects-passed-in-to-the-ar), but I find this section doesn't receive enough attention, maybe because it's relatively hidden.

The large number of issues posted by people on stackoverflow/github on this subject might be an indicative of some of the small but important details not getting surfaced enough. (I'm not blaming anybody, just raising awarness.)

**Comment by gitartur** [comment]
intiValueText - just a string and can be obtained from another model.

**Comment by whmemon** [comment]
@gitartur  Its correct. I removed Options and got the result. #37
