### ISSUE TITLE
Can't type anything if select2 in modal

### ISSUE THREAD

**Issue by embambols** [kartik-v/yii2-widget-select2#41]
After recent updates typing wasn't working in any of my select2 widgets that were inside bootstrap modals. Then I found this solution which seems to have worked for me: https://github.com/select2/select2/issues/1436

It was working fine before I did the update on everything and now I don't know what the cause of the problem is (either update of select2 widget or yii2 update), but since that solution is from almost 2 years ago I have a feeling that the problem is somewhere in your widget, because it was updated very recently.

**Comment by kartik-v** [comment]
You need to check the demos and docs pages for the widget.

The Select2 widget works perfectly with modal. You need to set the Modal markup correctly for it to work. [Check the demo page and scroll down to button for example for Select2 inside a MODAL](http://demos.krajee.com/widget-details/select2#usage-advanced).

Note the important setting for the Modal dialog... the `tabindex` must NOT be set and must be set to `false` as shown.

**Comment by embambols** [comment]
Ok. Thanks. It's just that it worked fine before, even without setting 'tabindex' => false. Have quite few places to update now :)

**Comment by sankam-nikolya** [comment]
thx

**Comment by elviskudo** [comment]
sorry for open this issue again,
now i found that problem again
cannot any typing on this widget in modal
and i see tab-index=-1
how can i solve this problem, thanks

**Comment by alvarolordelo** [comment]
how to set it required like HTML 5 validation
'required' => 'required' inside options isn't working
it should shown a required pop-up 

<?=
    $form->field($model, 'end_cidade_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\modulos\estoque\models\EndCidade::find()->where(['end_estado_id' => $model->end_estado_id])->orderBy('name')->asArray()->all(), 'id', 'name'),
        'options' => [
            'required' => 'required',
            'placeholder' => 'Selecione a cidade'
        ],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

**Comment by Starite** [comment]
Can't type anything if select2 in modal when using Firefox, Chrome works fine. Can you help me with this? thank you!

**Comment by sebastian-velasquez** [comment]
https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal

**Comment by robov** [comment]
Although I have it working in a bootstap modal... it works in chrome... but not in firefox...
Any ideas ?

**Comment by robov** [comment]
The dropdown is shown correctly, but I cannot type anything

**Comment by morrow95** [comment]
Have run into this problem again now that I am using Bootstrap 4.  All of the 'old' solutions which worked with Bootstrap 3 no longer work for me.  What I have tried so far : 

- removing tab-index from modal-body

- using $.fn.modal.Constructor.prototype.enforceFocus = function() {}; **this was my BS3 solution that worked and no longer does**

- using $.fn.modal.Constructor.prototype.enforceFocus = $.noop;

Does anyone have the search input working in a Bootstrap 4 modal?  Please let me know what you are doing.

**Comment by dzona** [comment]
``$.fn.modal.Constructor.prototype.enforceFocus = $.noop;``

**Comment by kartik-v** [comment]
You may want to set `dropdownParent` property of Select2 to the Modal Dialog identifier for addressing this (for example):

```php
echo Select2::widget([ 
    'pluginOptions' => [
        'dropdownParent' => '$("#modalDialogId")',
    ],
   // your other select2 widget settings
]);
```

**Comment by Hannaametist** [comment]
I wrote such, but see in console, that:
Error: Syntax error, unrecognized expression: $("#asset_704")

My code:
`'pluginOptions' => ['dropdownParent' => '$("#asset_704")'],`

**Comment by lieszkol** [comment]
Kartik's last example is the PROPER solution of the three, but it should really be:

```
echo Select2::widget([ 
    'pluginOptions' => [
        'dropdownParent' => new JsExpression('$("#modalDialogId")'),
    ],
   // your other select2 widget settings
]);
```
(of course you should substitute modalDialogId with the actual ID of the modal dialog)

**Summarizing it all:**
The problem is Bootstrap Modal inserting some js that grabs the focus of anything not inside of the modal. The Select2 drop-down is actually rendered outside of the Modal DOM element. There are three ways to fix this:

1) Make sure that the rendered modal does not have tabIndex="whatever" inside of it. This is the solution employed in Kartik's docs here: ([](http://demos.krajee.com/widget-details/select2#usage-advanced))
 
```
Modal::begin([
'options' => [
'id' => 'kartik-modal',
'tabindex' => false, 
...
```

This is also the "accepted" solution here: [](https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal)
Unfortunately, it is a hack and has some side-effects like breaking the ESC key to exit the modal, and scrolling issues if the modal is very long.

2) It is also possible to disable the Bootstrap Modal from trying to prevent focus from other elements when it's shown:

```
// Do this before you initialize any of your modals
$.fn.modal.Constructor.prototype.enforceFocus = function() {};

```
This is detailed also on the link above as well as here: [](https://select2.org/troubleshooting/common-problems)
But again, this is a hack and has side-effects.

3) The PROPER solution is to let Select2 know that it should attach itself to the modal (or one of it's children, like the modal body).
This is also described in the two links above and mentioned above by Kartik.

To implement the proper solution that doesn't break intended bootstrap modal functionality, do what is written at the top of this post!
