### ISSUE TITLE
update

### ISSUE THREAD

**Issue by logsanctuary** [kartik-v/yii2-widget-select2#76]
Hello,

I use select2 plugin in a column of your grid view module 

Since the last release, the column is too large compared to the width page. I fixe the value in pourcentage but there are a problem.

Could you help me ?

Thank

**Comment by Bhoft** [comment]
i have the same issue since 2.0.3 the problem is due to the loading indicator the select input will be set to display none.
the select2 js code then tries to get the width of the select input and fail and would return the complete outerwidth in my case 2560px due to my screen resolution 2560x1440px.

if I disable the pluginLoading or remove that display none css style it works again flawlessly.
````
       if ($this->pluginLoading) {
            $this->_loadIndicator = '<div class="kv-plugin-loading loading-' . $this->options['id'] . '">&nbsp;</div>';
            Html::addCssStyle($this->options, 'display:none');
        }
````

**Comment by kartik-v** [comment]
Duplicate to #73.

**Comment by Bhoft** [comment]
strange i have updated to 2.0.4 or the dev version of the select2 widget, cleared the assets and still have the width problem in my grid. Maybe it is because of a fluid design?
I just have a gridview with this gridcolumn.
I have tried different width settings for the th column and the select item.
If pluginLoading is set to true it (which is default) the column would be expanded to my full monitor resolution.
```
[
            'attribute' => 'organizer_id',
            'vAlign'=>'middle',
            //'width'=>'200px',
            'width'=>'10%',
            //'headerOptions'=> ['style' => 'width: 200px; white-space: nowrap;'],
            'header' => \Yii::t('app', 'Organizer'),
            'format' => 'raw',
            'filterType'=>GridView::FILTER_SELECT2,
            'filter'=>ArrayHelper::map(Organizer::find()->orderBy('name')->asArray()->all(), 'id', 'name'),
            'filterWidgetOptions'=>[
                //'pluginLoading' => false,
                'pluginOptions' => ['allowClear' => true],
            ],
            'filterInputOptions' => ['placeholder' => \Yii::t('app', 'Any Organizer'), 'class'=> 'input-md', 'width'=>'10%',],
            'value'=>function ($data, $key, $index, $widget) {
                return $this->render('//system/columnviews/_organizer', ['data' => $data->organizer]);
            },
        ],
```

this is the example code in your demo (as displayed by the gridcolumns setup button)
```
[
    'attribute'=>'author_id', 
    'vAlign'=>'middle',
    'width'=>'180px',
    'value'=>function ($model, $key, $index, $widget) { 
        return Html::a($model->author->name,  
            '#', 
            ['title'=>'View author detail', 'onclick'=>'alert("This will open the author page.\n\nDisabled for this demo!")']);
    },
    'filterType'=>GridView::FILTER_SELECT2,
    'filter'=>ArrayHelper::map(Author::find()->orderBy('name')->asArray()->all(), 'id', 'name'), 
    'filterWidgetOptions'=>[
        'pluginOptions'=>['allowClear'=>true],
    ],
    'filterInputOptions'=>['placeholder'=>'Any author'],
    'format'=>'raw'
],
```

I can't see a difference.

**Comment by Bhoft** [comment]
I still think this is a bug which is coming from the loading indicator. Because this hide's the select html item and then the select2.js code couldn't get the item width.
I have added some console logs in the _resolveWidth funktion which is called in the _placeContainer function.

wrong width when pluginLoading is set to true (which hides the select item)
![with_pluginloading](https://cloud.githubusercontent.com/assets/1777147/10068774/9212f2cc-62a7-11e5-934c-bbe032e077c2.jpg)

and correct width when i disable the pluginLoading 
![without_pluginloading](https://cloud.githubusercontent.com/assets/1777147/10068776/9499ec9e-62a7-11e5-9f0f-fdf08c36275a.jpg)

**Comment by Bhoft** [comment]
Ok after i have replaced my "kartik-v/yii2-grid": "*", with "kartik-v/yii2-grid": "@dev", in the composer.json and have done an composer update the issue was fixed.

These 2 things were updated.
  - Removing kartik-v/yii2-grid (v3.0.6)
  - Installing kartik-v/yii2-grid (dev-master 913fde8)
    Cloning 913fde8fbe41bf998d53a88d0443e25e1e696194

  - Removing kartik-v/yii2-builder (v1.6.1)
  - Installing kartik-v/yii2-builder (v1.6.0)

**Comment by kartik-v** [comment]
That's what I have been precisely mentioning in all the issues.. update to the latest release of the related extensions....

**Comment by kartik-v** [comment]
That's what I have been precisely mentioning in all these similar issues..

**update to the latest release of the related extensions**

For example  latest release for `yii2-grid` is v3.0.7  -- while you had release v3.0.6

**Comment by Bhoft** [comment]
The problem is I prefer to use "stable" releases. Gridview is set to 3.0.6 stable, select2 is 2.0.3.
I had updated to the 2.0.4 of the select2 widget as i mentioned above after you have said I should update to the latest release. Didn't know that have to update gridview to the dev release as well ;)

But glad this issue is now solved.
When will both widget be changed to "stable" with those versions?
