### ISSUE TITLE
Upgrade jQuery plugin

### ISSUE THREAD

**Issue by bupy7** [kartik-v/yii2-widget-select2#8]
hi! Please, upgrade jQuery plugin. =)

And, Why you not use Bower?

**Comment by kartik-v** [comment]
I cannot use bower - because I have other added CSS enhancements from my side to the plugin including the need minimized source assets (not available in source repo - there is a PR to include minified assets in source repo - probably will be resolved in release 4.0)... till then it has to be manually periodically updated.

**Comment by bupy7** [comment]
too bad..

**Comment by kartik-v** [comment]
Closing it until source plugin is updated.
